name: ZHENG Zhong
markdown: kramdown
highlighter: rouge
exclude: ['Rakefile', 'README.md', 'config.rb', '*.bat', '*.bak', 'scripts']
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
paginate: 10
paginate_path: /blog/page:num

google_analytics_id: UA-356705-1

kramdown:
   input: GFM
   hard_wrap: false

gems:
   - jekyll-coffeescript
   - jekyll-paginate

sass:
  sass_dir: _sass
  style: :compressed
